## nature reward function
TIME_PENALITY = -1  ### -.01
RAND_PENALITY = 0    ## this will only be in the safe mode training once ghosts are in disable it
PELLET_LOST_PENALITY = 0
HIT_WALL_PENALITY = -1 

PELLET_REWARD_UPDATE = 0
PELLET_REWARD = 1
POWERPELLET_REWARD = 1
FRUIT_REWARD = 1
FINISH_LEVEL_REWARD = 500


GHOST_PENALITY = -50
GHOST_REWARD = 7.5
GHOST_UPDATE_REWARD = 0.5
GHOST_UPDATE_PENALITY = 2
GHOST_REWARDS = {GHOST_PENALITY : 1 , GHOST_REWARD : 2 , GHOST_REWARD+GHOST_UPDATE_REWARD : 3 , GHOST_REWARD+2*GHOST_UPDATE_REWARD : 4 ,  GHOST_REWARD+3*GHOST_UPDATE_REWARD : 5}